server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

axon:
  amqp:
    exchange: bank.events